version: '3.8'

services:
  gateway:
    image: 'nginx:latest'
    container_name: gateway
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./www/:/etc/nginx/www/